apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: house-predictor
  name: house-predictor
spec:
  ports:
  - name: "8000"
    nodePort: 30100
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: house-predictor
  type: NodePort
status:
  loadBalancer: {}