apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      # 👇 Add initContainer to create directories and fix permissions
      initContainers:
      - name: init-mlflow-storage
        image: busybox
        command:
          - sh
          - -c
          - |
            mkdir -p /mlflow/db /mlflow/artifacts && chmod -R 777 /mlflow
        volumeMounts:
          - name: mlflow-pvc
            mountPath: /mlflow

      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        ports:
          - containerPort: 5000
        command: ["python", "-m", "mlflow", "server"]
        args:
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "5000"
          - "--backend-store-uri"
          - "sqlite:////mlflow/db/mlflow.db"
          - "--default-artifact-root"
          - "/mlflow/artifacts"
        volumeMounts:
          - name: mlflow-pvc
            mountPath: /mlflow

      volumes:
      - name: mlflow-pvc
        persistentVolumeClaim:
          claimName: mlflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000
