name: Build and Push Streamlit App

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
        IMAGE_NAME=docker.io/${{ vars.DOCKERHUB_USERNAME }}/streamlit-app

        echo "Building image $IMAGE_NAME:$COMMIT_HASH..."
        docker build -t $IMAGE_NAME:$COMMIT_HASH -t $IMAGE_NAME:latest -f streamlit_app/Dockerfile .

        echo "Pushing to DockerHub..."
        docker push $IMAGE_NAME:$COMMIT_HASH
        docker push $IMAGE_NAME:latest
