name: Build, Push, and Deploy Streamlit App Windows

on:
  workflow_dispatch:    # for manual runs
  repository_dispatch:
    types: [deploy-streamlit]
#  push:
#    branches:
#      - main 

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.ref || github.ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    
    - name: Build and Push Docker image
      shell: powershell
      run: |
        $COMMIT_HASH = $env:GITHUB_SHA.Substring(0,7)
        $IMAGE_NAME = "docker.io/${{ vars.DOCKERHUB_USERNAME }}/streamlit-app"

        Write-Host "Building image $IMAGE_NAME:$COMMIT_HASH..."
        docker build -t $IMAGE_NAME:$COMMIT_HASH -t $IMAGE_NAME:latest -f streamlit_app\Dockerfile .

        Write-Host "Pushing to DockerHub..."
        docker push $IMAGE_NAME:$COMMIT_HASH
        docker push $IMAGE_NAME:latest

    - name: Configure kubectl 
      shell: powershell
      run: |
        $KubePath = "$HOME\.kube"
        New-Item -ItemType Directory -Force -Path $KubePath
        Set-Content -Path "$KubePath\config" -Value "${{ secrets.KUBECONFIG_CONTENT }}"


    - name: Verify cluster access
      run: |
        kubectl get nodes
        kubectl get ns 

    
    - name: Deploy new Streamlit image
      shell: powershell
      run: |
        $IMAGE_NAME = "docker.io/${{ vars.DOCKERHUB_USERNAME }}/streamlit-app:latest"
        Write-Host "Deploying Streamlit app using image $IMAGE_NAME"
    
        # Check if the deployment exists
        $deploymentExists = kubectl get deployment streamlit -o name 2>$null
        if (-not $deploymentExists) {
          Write-Host "Streamlit deployment not found. Creating it..."
          kubectl create deployment streamlit --image=$IMAGE_NAME | Out-Null
          kubectl expose deployment streamlit --type=LoadBalancer --port=8501 --target-port=8501 | Out-Null
        } else {
          Write-Host "Updating existing Streamlit deployment..."
          kubectl set image deployment/streamlit streamlit=$IMAGE_NAME --record
        }
    
        # Wait for rollout to finish
        kubectl rollout status deployment/streamlit
