name: MLOps Pipeline Windows

on:
  workflow_dispatch:
    inputs:
      run_all:
        description: 'Run all jobs'
        required: false
        default: 'true'
      run_data_processing:
        description: 'Run data processing job'
        required: false
        default: 'false'

      run_model_training:
        description: 'Run model trainnig job'
        required: false
        default: 'false'
      run_build_and_publish:
        description: 'Run build and publish job'
        required: false
        default: 'false'
  release:
    types: [created]
    branches: [ main ]
    tags: [ 'v*.*.*' ]


jobs:
  data-processing:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process Data 
      shell: powershell
      run: |
        python src\data\run_processing.py `
        --input data\raw\house_data.csv `
        --output data\processed\cleaned_house_data.csv

    - name: Engineer Features 
      shell: powershell
      run: |
        python src\features\engineer.py `
        --input data\processed\cleaned_house_data.csv `
        --output data\processed\featured_house_data.csv `
        --preprocessor models\trained\preprocessor.pkl

    - name: Upload Processed Data 
      uses: actions/upload-artifact@v4
      with:
        name: processed-data
        path: data/processed/featured_house_data.csv

    - name: Upload Preprocessor 
      uses: actions/upload-artifact@v4
      with: 
        name: preprocessor
        path: models/trained/preprocessor.pkl

  model-training:
    needs: data-processing
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download processed data 
      uses: actions/download-artifact@v5
      with:
        name: processed-data
        path: data/processed/

    - name: Deploy Persistent MLflow Server
      shell: powershell
      run: |
        # Apply deployment yaml (create or update)
        kubectl apply -f .github/workflows/mlflow-deployment.yaml

        # Wait until pod is ready
        kubectl wait --for=condition=available deployment/mlflow --timeout=300s

        # Start port-forward in background
        Start-Process powershell -ArgumentList "kubectl port-forward svc/mlflow 5000:5000" -NoNewWindow

        # Wait for MLflow to respond
        $maxRetries = 20
        $waitSec = 5
        $uri = "http://127.0.0.1:5000"

        for ($i=0; $i -lt $maxRetries; $i++) {
            try {
                Invoke-WebRequest "$uri/health" -UseBasicParsing -TimeoutSec 5
                Write-Host "MLflow is ready at $uri"
                break
            } catch {
                Write-Host "Waiting for MLflow to start... ($i)"
                Start-Sleep -Seconds $waitSec
            }
        }

    - name: Train Model 
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path models

        python src\models\train_model.py `
        --config configs\model_config.yaml `
        --data data\processed\featured_house_data.csv `
        --models-dir models `
        --mlflow-tracking-uri "http://127.0.0.1:5000"

    - name: Upload Trained Model 
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/

    - name: Clean up MLFlow
      shell: powershell
      run: |
        docker stop mlflow-server2; docker rm mlflow-server2
  
  build-and-publish:
    needs: model-training
    runs-on: self-hosted

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v2

    - name: Download Trained Model 
      uses: actions/download-artifact@v5 
      with:
        name: trained-model
        path: models/

    - name: Download preprocessor
      uses: actions/download-artifact@v5
      with:
        name: preprocessor
        path: models/trained/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and test Docker image
      shell: powershell
      run: |
        $COMMIT_HASH = $env:GITHUB_SHA.Substring(0,7)
        $IMAGE = "docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:$COMMIT_HASH"
        docker build -t $IMAGE -f Dockerfile .
        docker run -d -p 8000:8000 --name test-api $IMAGE
        for ($i=0; $i -lt 10; $i++) {
          try {
            Invoke-WebRequest http://localhost:8000/health -UseBasicParsing -TimeoutSec 5
            break
          } catch {
            Start-Sleep -Seconds 5
          }
        }
        docker logs test-api

    - name: Clean up Test Container
      shell: powershell
      run: |
        docker stop test-api; docker rm test-api

    - name: Log in to Github Container Registry
      uses: docker/login-action@v3
      with: 
        registry: docker.io
        username: ${{vars.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Push Docker image to DockerHub 
      shell: powershell
      run: |
        $COMMIT_HASH = $env:GITHUB_SHA.Substring(0,7)
        $IMAGE = "docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:$COMMIT_HASH"
        docker tag $IMAGE "docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:latest"
        docker push $IMAGE
        docker push "docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:latest"

    - name: Set up kubectl 
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    - name: Configure kubectl
      shell: powershell
      run: |
        $KubePath = "$HOME\.kube"
        New-Item -ItemType Directory -Force -Path $KubePath
        Set-Content -Path "$KubePath\config" -Value "${{ secrets.KUBECONFIG_CONTENT }}"
        kubectl get nodes

    - name: Deploy FastAPI to k3d
      shell: powershell
      run: |
        $COMMIT_HASH = $env:GITHUB_SHA.Substring(0,7)
        $IMAGE = "docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:$COMMIT_HASH"

        # Deploy FastAPI
        $deployment = kubectl get deployment house-predictor --ignore-not-found
        if (-not $deployment) {
            kubectl create deployment house-predictor --image=$IMAGE
        } else {
            kubectl set image deployment/house-predictor house-predictor=$IMAGE
        }

        kubectl expose deployment house-predictor --type=NodePort --port=8000 --target-port=8000 --ignore-existing

        # Print FastAPI NodePort
        $fastapiPort = kubectl get svc house-predictor -o jsonpath="{.spec.ports[0].nodePort}"
        Write-Host "FastAPI available at http://localhost:$fastapiPort"

    - name: Trigger Streamlit workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repository: ${{ github.repository }}
        event-type: deploy-streamlit
        client-payload: '{"ref": "main"}'






